export const Routes = {
    SPLASH_SCREEN: 'splashScreen',
    LOGIN_SCREEN: 'loginScreen',
    REGISTER_SCREEN: 'registerScreen',
    MAIN_TAB: 'mainTab',
    HOME_SCREEN: 'homeScreen',
    FRIEND_REQUEST_SCREEN: 'friendRequestScreen',
    USER_PROFILE_SCREEN: 'userProfileScreen',
    NOTIFICATION_SCREEN: 'notificationScreen',
    SHORTCUT_SCREEN: 'shortcutScreen',
    HOME_TAB: 'homeTab',
    FRIEND_REQUEST_TAB: 'friendRequestTab',
    USER_PROFILE_TAB: 'userProfileTab',
    NOTIFICATION_TAB: 'notificationTab',
    SHORTCUT_TAB: 'shortcutTab',
    FULL_POST_TOOL_SCREEN: 'fullPostToolScreen',
    COMMENT_SCREEN: 'commentScreen',
    POST_DETAIL_SCREEN: 'postDetailScreen',
};
